---
language: ruby
before_script: 'bundle exec rake fixture:prepare'
script: 'SPEC_OPTS="--format documentation" bundle exec rake spec'
notifications:
  email: false
rvm:
  - 1.9.3
  - 1.8.7
env:
  - PUPPET_VERSION=2.7.9  # Puppet Enterprise 2.0.3
  - PUPPET_VERSION=2.7.12 # Puppet Enterprise 2.5.3
  - PUPPET_VERSION=2.7.19 # Puppet Enterprise 2.6.1 & 2.7.2
  - PUPPET_VERSION=2.7.21 # Puppet Enterprise 2.8.1
  - PUPPET_VERSION=3.1.0
  - PUPPET_VERSION=3.2.1
matrix:
  exclude:
    - {rvm: 1.9.3, env: PUPPET_VERSION=2.7.9}
    - {rvm: 1.9.3, env: PUPPET_VERSION=2.7.12}
    - {rvm: 1.9.3, env: PUPPET_VERSION=2.7.19}
    - {rvm: 1.9.3, env: PUPPET_VERSION=2.7.21}
